pipeline {
  agent none
  stages {
    stage('docker-package'){
      agent any
      steps {
        echo 'Packaging vote app with Docker'
        script {
          docker.withRegistry('https://index.docker.io/v1/','dockerlogin') {
            def imageName = "matheusmbar/vote:v${env.BUILD_ID}"
            echo "Image name: ${imageName}"
            def workerImage = docker.build("${imageName}", "./vote")
            workerImage.push()
            workerImage.push("latest")
          }
        }
      }
    }
  }
}
