pipeline {
  agent {
    docker {
      image 'maven:3.6.3-jdk-8-slim'
      args '-v $HOME/.m2:/root/.m2'
    }
  }
  stages {
    stage("build") {
      when{
        changeset "**/worker/**"
      }
      steps {
        echo 'Compiling worker app'
        dir('worker') {
          sh 'mvn compile'
        }
      }
    }
    stage("test") {
      when{
        changeset "**/worker/**"
      }
      steps {
        echo 'Running Unit Tests on worker app'
        dir('worker') {
          sh 'mvn clean test'
        }
      }
    }
    stage("package") {
      when{
        branch 'master'
        changeset "**/worker/**"
      }
      steps {
        echo 'Packaging worker app'
        dir('worker') {
          sh 'mvn package -DskipTests'
          archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
        }
      }
    }
    stage('docker-package'){
      agent any
      steps {
        echo 'Packaging worker app with Docker'
        script {
          def workerImage = docker.build("matheus/worker:v${env.BUILD_ID}", "./worker")
          echo "Image: ${workerImage}"
        }
      }
    }
  }
  post {
    always {
      echo 'Building multibranch pipeline for worker is completed..'
    }
  }
}
