pipeline {
  agent none

  stages {
    stage("build") {
      when{
        changeset "**/worker/**"
      }
      agent {
        docker {
          image 'maven:3.6.3-jdk-8-slim'
          args '-v $HOME/.m2:/root/.m2'
        }
      }
      steps {
        echo 'Compiling worker app'
        dir('worker') {
          sh 'mvn compile'
        }
      }
    }
    stage("test") {
      when{
        changeset "**/worker/**"
      }
      agent {
        docker {
          image 'maven:3.6.3-jdk-8-slim'
          args '-v $HOME/.m2:/root/.m2'
        }
      }
      steps {
        echo 'Running Unit Tests on worker app'
        dir('worker') {
          sh 'mvn clean test'
        }
      }
    }
    stage("package") {
      when{
        branch 'master'
        changeset "**/worker/**"
      }
      agent {
        docker {
          image 'maven:3.6.3-jdk-8-slim'
          args '-v $HOME/.m2:/root/.m2'
        }
      }
      steps {
        echo 'Packaging worker app'
        dir('worker') {
          sh 'mvn package -DskipTests'
          archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
        }
      }
    }
    stage('docker-package'){
      agent any
      when {
        changeset '**/worker/**'
        branch 'master'
      }
      steps {
        echo 'Packaging worker app with Docker'
        script {
          docker.withRegistry('https://index.docker.io/v1/','dockerlogin') {
            def imageName = "matheusmbar/worker:v${env.BUILD_ID}"
            echo "Image name: ${imageName}"
            def workerImage = docker.build("${imageName}", "./worker")
            workerImage.push()
            workerImage.push("latest")
          }
        }
      }
    }
  }
  post {
    always {
      echo 'Building multibranch pipeline for worker is completed..'
    }
  }
}
